spring:
  redis:
    host: 10.214.199.218
    port: 6338
    password: qiniu1024
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    redisson:
      config: |
        singleServerConfig:
          address: redis://10.214.199.218:6338
          connectionMinimumIdleSize: 11
          password: qiniu1024
          database: 0
        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"
server:
  port: 28003