server:
  port: 28005

qiniu:
  access-key: bgQHEdgUnYo-bTIEP7OXwMxphw0p7pwtO6j9v2Yq
  secret-key: xxx
  bucket: niuktok
  expire-times: 3600
  useHttps: false
  domain: s3nj7lcag.bkt.clouddn.com
  put-policy:
    return-body: "{\"key\":\"$(key)\",\"hash\":\"$(etag)\"}"