version: '3'
services:
  gateway-service:
    build: 
      context: ../gateway-service
      dockerfile: dockerfile
    image: niuktok-gateway-service:${env}_${version}
    container_name: niuktok-gateway-service-${env}-${version}
    ports:
      - "${gateway_service_port}:${gateway_service_port}"
    environment:
      - envType=${env}
    network_mode: host
  auth-service:
    build: 
      context: ../auth-service
      dockerfile: dockerfile
    image: niuktok-auth-service:${env}_${version}
    container_name: niuktok-auth-service-${env}-${version}
    ports:
      - "${auth_service_port}:${auth_service_port}"
    environment:
      - envType=${env}
    network_mode: host
  redis-service:
    build: 
      context: ../redis-service
      dockerfile: dockerfile
    image: niuktok-redis-service:${env}_${version}
    container_name: niuktok-redis-service-${env}-${version}
    ports:
      - "${redis_service_port}:${redis_service_port}"
    environment:
      - envType=${env}
    network_mode: host
  user-service:
    build: 
      context: ../user-service
      dockerfile: dockerfile
    image: niuktok-user-service:${env}_${version}
    container_name: niuktok-user-service-${env}-${version}
    ports:
      - "${user_service_port}:${user_service_port}"
    environment:
      - envType=${env}
    network_mode: host